CarePortal.Web/Controllers/DashboardController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CarePortal.Web.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ILogger _logger;

        public DashboardController(ILogger<DashboardController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

CarePortal.Web/Controllers/FeedController.cs
using CarePortal.Data.Models;
using CarePortal.Data.Response;
using CarePortal.Data.ViewModels;
using CarePortal.Web.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Threading.Tasks;

namespace CarePortal.Web.Controllers
{
    public class FeedController : Controller
    {
        private readonly ILogger _logger;

        public FeedController(ILogger<FeedController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                UserModel userModel = new UserModel();
                userModel.Id = HttpContext.Session.GetObject(StorageType.UserId).ToString();//LocalStorageExtensions.Get(StorageType.UserId);
                userModel.Role = HttpContext.Session.GetObject(StorageType.Role).ToString();//LocalStorageExtensions.Get(StorageType.Role);
                userModel.Picture = HttpContext.Session.GetObject(StorageType.Picture).ToString();//LocalStorageExtensions.Get(StorageType.Picture);

                string response = await APICallerExtensions.APICallAsync("Feed/Index", userModel, false, HttpContext.Session.GetObject(StorageType.Token).ToString());
                if (response.ToLower().Contains("exception:"))
                {
                    ModelState.AddModelError(string.Empty, response);
                    return View();
                }
                var content = JsonConvert.DeserializeObject<SingleResponse<FeedPageModel>>(response);
                if (!content.DidError)
                {
                    //content.Model.UserName = HttpContext.Session.GetObject(StorageType.Name).ToString();//LocalStorageExtensions.Get(StorageType.Name);
                    //content.Model.UserPicture = HttpContext.Session.GetObject(StorageType.Picture).ToString();//LocalStorageExtensions.Get(StorageType.Picture);
                    content.Model.UserRole = HttpContext.Session.GetObject(StorageType.Role).ToString();//LocalStorageExtensions.Get(StorageType.Role);

                    return View(content.Model);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, content.Message);
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }


        [HttpPost]
        public async Task<JsonResult> AddFeed(string data, int departmentId)
        {
            try
            {
                FeedViewModel addFeedViewModel = new FeedViewModel();
                addFeedViewModel.UserId = HttpContext.Session.GetObject(StorageType.UserId).ToString();//LocalStorageExtensions.Get(StorageType.UserId);
                addFeedViewModel.Data = data;
                addFeedViewModel.DepartmentId = departmentId;
                string response = await APICallerExtensions.APICallAsync("Feed/AddFeed", addFeedViewModel, false, HttpContext.Session.GetObject(StorageType.Token).ToString());
                if (response.ToLower().Contains("exception:"))
                {
                    ModelState.AddModelError(string.Empty, response);
                    return Json(new
                    {
                        result = false,
                        error = response
                    });
                }
                var content = JsonConvert.DeserializeObject<SingleResponse<Feed>>(response);
                if (!content.DidError)
                {
                    return Json(new
                    {
                        content.Model,
                    });
                }
                else
                {
                    return Json(new
                    {
                        result = false,
                        error = content.ErrorMessage
                    });
                }
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    result = false,
                    error = ex.Message
                });
            }
        }

        public async Task<JsonResult> LoadMore(int PageNumber, int PageSize)
        {
            try
            {
                FeedPageModel loadMoreFeedPageModel = new FeedPageModel();
                loadMoreFeedPageModel.UserId = HttpContext.Session.GetObject(StorageType.UserId).ToString();//LocalStorageExtensions.Get(StorageType.UserId);
                loadMoreFeedPageModel.PageNumber = PageNumber;
                loadMoreFeedPageModel.PageSize = PageSize;
                string response = await APICallerExtensions.APICallAsync("Feed/LoadMore", loadMoreFeedPageModel, false, HttpContext.Session.GetObject(StorageType.Token).ToString());
                if (response.ToLower().Contains("exception:"))
                {
                    ModelState.AddModelError(string.Empty, response);
                    return Json(new
                    {
                        result = false,
                        error = response
                    });
                }
                var content = JsonConvert.DeserializeObject<SingleResponse<FeedPageModel>>(response);
                if (!content.DidError)
                {
                    return Json(new
                    {
                        content.Model,
                    });
                }
                else
                {
                    return Json(new
                    {
                        result = false,
                        error = content.ErrorMessage
                    });
                }
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    result = false,
                    error = ex.Message
                });
            }
        }

        [HttpPost]
        public async Task<JsonResult> AddFeedResponse(int feedId, int feedResponse)
        {
            try
            {
                AddFeedResponse addFeedResponse = new AddFeedResponse();
                addFeedResponse.UserId = HttpContext.Session.GetObject(StorageType.UserId).ToString();//LocalStorageExtensions.Get(StorageType.UserId);
                addFeedResponse.FeedId = feedId;
                addFeedResponse.Response = feedResponse;
                string response = await APICallerExtensions.APICallAsync("Feed/AddFeedResponse", addFeedResponse, false, HttpContext.Session.GetObject(StorageType.Token).ToString());
                if (response.ToLower().Contains("exception:"))
                {
                    ModelState.AddModelError(string.Empty, response);
                    return Json(new
                    {
                        result = false,
                        error = response
                    });
                }
                var content = JsonConvert.DeserializeObject<SingleResponse<FeedResponse>>(response);
                if (!content.DidError)
                {
                    return Json(new
                    {
                        content.Model,
                    });
                }
                else
                {
                    return Json(new
                    {
                        result = false,
                        error = content.ErrorMessage
                    });
                }
            }
            catch (Exception ex)
            {

                return Json(new
                {
                    result = false,
                    error = ex.Message
                });
            }
        }
        [HttpPost]
        public async Task<JsonResult> AddComment(int feedId, string newComment)
        {
            try
            {
                CommentsViewModel addCommentViewModel = new CommentsViewModel();
                addCommentViewModel.UserId = HttpContext.Session.GetObject(StorageType.UserId).ToString();//LocalStorageExtensions.Get(StorageType.UserId);

                addCommentViewModel.FeedId = feedId;
                addCommentViewModel.Comments = newComment;

                var userName = HttpContext.Session.GetObject(StorageType.Name).ToString();//LocalStorageExtensions.Get(StorageType.Name);
                var imageURL = HttpContext.Session.GetObject(StorageType.Picture).ToString();//LocalStorageExtensions.Get(StorageType.Picture);

                string response = await APICallerExtensions.APICallAsync("Feed/AddComment", addCommentViewModel, false, HttpContext.Session.GetObject(StorageType.Token).ToString());
                if (response.ToLower().Contains("exception:"))
                {
                    ModelState.AddModelError(string.Empty, response);
                    return Json(new
                    {
                        result = false,
                        error = response
                    });
                }
                var content = JsonConvert.DeserializeObject<SingleResponse<Comment>>(response);
                if (!content.DidError)
                {
                    return Json(new
                    {
                        content.Model,
                        userName,
                        imageURL
                    });
                }
                else
                {
                    return Json(new
                    {
                        result = false,
                        error = content.ErrorMessage
                    });
                }
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    success = false,
                    error = ex.Message
                });
            }
        }
    }
}

CarePortal.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using System.Linq;
using CarePortal.Web.Extensions;
using Newtonsoft.Json;
using CarePortal.Data.Models;
using CarePortal.Data.Response;
using CarePortal.Data.ViewModels;
using Microsoft.Extensions.Logging;

namespace CarePortal.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly ILogger _logger;

        public SearchController(ILogger<SearchController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                UserModel userModel = new UserModel();
                userModel.Id = HttpContext.Session.GetObject(StorageType.UserId).ToString();//LocalStorageExtensions.Get(StorageType.UserId);
                userModel.Role = HttpContext.Session.GetObject(StorageType.Role).ToString();//LocalStorageExtensions.Get(StorageType.Role);
                string response = await APICallerExtensions.APICallAsync("Search/Index", userModel, false, HttpContext.Session.GetObject(StorageType.Token).ToString());
                if (response.ToLower().Contains("exception:"))
                {
                    ModelState.AddModelError(string.Empty, response);
                    return View();
                }
                var content = JsonConvert.DeserializeObject<ListResponse<SearchViewModel>>(response);
                if (!content.DidError)
                {
                    return View(content.Model);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, content.Message);
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }

        [HttpPost]
        public async Task<JsonResult> SearchDoctors(string searchText)
        {
            try
            {
                if (string.IsNullOrEmpty(searchText))
                {
                    searchText = string.Empty;
                }
                SearchViewModel searchViewModel = new SearchViewModel();
                searchViewModel.SearchText = searchText;
                string response = await APICallerExtensions.APICallAsync("Search/SearchDoctors", searchViewModel, false, HttpContext.Session.GetObject(StorageType.Token).ToString());
                if (response.ToLower().Contains("exception:"))
                {
                    ModelState.AddModelError(string.Empty, response);
                    return Json(new
                    {
                        isSuccessfull = false,
                        totalRecords = 0,
                        errorMessage = response,
                        doctorsList = string.Empty
                    });
                }
                var content = JsonConvert.DeserializeObject<ListResponse<SearchViewModel>>(response);
                if (!content.DidError)
                {
                    return Json(new
                    {
                        isSuccessfull = true,
                        totalRecords = content.Model.Count(),
                        errorMessage = response,
                        doctorsList = content.Model
                    });
                }
                else
                {
                    ModelState.AddModelError(string.Empty, content.Message);
                    return Json(new
                    {
                        isSuccessfull = false,
                        totalRecords = 0,
                        errorMessage = content.ErrorMessage,
                        doctorsList = string.Empty
                    });
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Json(new
                {
                    isSuccessfull = false,
                    totalRecords = 0,
                    errorMessage = ex.Message,
                    doctorsList = string.Empty
                });
            }
        }
    }
}

CarePortal.Web/Views/Shared/_Layout.cshtml
@using CarePortal.Web.Extensions
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewData["Title"] - Care Portal</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/css/skin-blue.min.css">
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @RenderSection("Styles", required: false)
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            @if (LocalStorageExtensions.Exists(StorageType.Token) && LocalStorageExtensions.Get(StorageType.Role) == "Admin")
            {
                <a asp-area="" asp-controller="Doctors" asp-action="Index" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>H</b>P</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Care</b>Portal</span>
                </a>
            }
            @if (LocalStorageExtensions.Exists(StorageType.Token) && LocalStorageExtensions.Get(StorageType.Role) == "Doctor")
            {
                <a asp-area="" asp-controller="Dashboard" asp-action="Index" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>H</b>P</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Care</b>Portal</span>
                </a>
            }
            @if (LocalStorageExtensions.Exists(StorageType.Token) && LocalStorageExtensions.Get(StorageType.Role) == "Patient")
            {
                <a asp-area="" asp-controller="Feed" asp-action="Index" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>H</b>P</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Care</b>Portal</span>
                </a>
            }
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                @*<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>*@
                <!-- Navbar Right Menu -->
                @await Html.PartialAsync("_LoginPartial")
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar Menu -->
                <ul class="sidebar-menu" data-widget="tree">
                    @if (LocalStorageExtensions.Exists(StorageType.Token) && LocalStorageExtensions.Get(StorageType.Role) == "Admin")
                    {
                        <li>
                            <a asp-area="" asp-controller="Doctors" asp-action="Index">Doctors</a>
                        </li>
                    }
                    @if (LocalStorageExtensions.Exists(StorageType.Token) && LocalStorageExtensions.Get(StorageType.Role) == "Doctor")
                    {
                        <li>
                            <a asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                    }
                    @if (LocalStorageExtensions.Exists(StorageType.Token) && (LocalStorageExtensions.Get(StorageType.Role) == "Doctor" || LocalStorageExtensions.Get(StorageType.Role) == "Patient"))
                    {
                        <li>
                            <a asp-area="" asp-controller="Feed" asp-action="Index">Feed</a>
                        </li>
                    }
                    @if (LocalStorageExtensions.Exists(StorageType.Token) && LocalStorageExtensions.Get(StorageType.Role) == "Patient")
                    {
                        <li>
                            <a asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Question" asp-action="Index">Question</a>
                        </li>
                    }
                    @if (LocalStorageExtensions.Exists(StorageType.Token) && (LocalStorageExtensions.Get(StorageType.Role) == "Doctor" || LocalStorageExtensions.Get(StorageType.Role) == "Patient"))
                    {
                        <li>
                            <a asp-area="" asp-controller="Conversation" asp-action="Index">Conversation</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Calendar" asp-action="Index">Calendar</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Finance" asp-action="Index">Finance</a>
                        </li>
                    }
                </ul>
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="container-fluid full-height">
                @RenderBody()
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong>Copyright &copy; 2019 Care Portal.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- JQUERY -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/jquery.cookie.js"></script>
    <script type="text/javascript">
        var UserId = "@LocalStorageExtensions.Get(StorageType.UserId)";
        var Username = "@LocalStorageExtensions.Get(StorageType.Name)";
        var UserRole = "@LocalStorageExtensions.Get(StorageType.Role)";
    </script>
    <!-- BOOTSTRAP -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/js/moment.js"></script>
    <script src="~/js/Util.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>